#!/usr/bin/perl

use 5.010;
use strict;
use utf8;
use warnings;

use Perinci::CmdLine;

our %SPEC;

$SPEC{foo} = {
    v => 1.1,
};
sub foo {
    my %args = @_;
    [200];
}

$SPEC{foo_fr} = {
    v => 1.1,
    summary => "Return something French",
};
sub foo_fr {
    my %args = @_;
    [200, "OK", "c'est intéressant!"];
}

$SPEC{foo_zh} = {
    v => 1.1,
    summary => "Return something Chinese",
};
sub foo_zh {
    my %args = @_;
    [200, "OK", "很有趣的！"];
}

Perinci::CmdLine->new(
    url => '/main/foo',
    subcommands => {
        sc1 => {
            url => '/main/foo',
            summary => 'Summary for sc1',
            tags => ['category:Foo'],
        },
        sc2_a_subcommand_with_a_rather_long_name => {
            url => '/main/foo',
            summary => 'Summary for sc2',
            tags => ['category:Foo'],
        },
        sc3 => {
            url => '/main/foo',
        },
        sc4 => {
            url => '/main/foo_fr',
            summary => 'Summary for sc4',
            "summary.alt.lang.id_ID" => 'Ringkasan untuk sc4',
            "summary.alt.lang.fr_FR" => 'Résumé pour sc4',
            "summary.alt.lang.zh_CN" => 'sc4的摘要',
            tags => ['category:Bar'],
            # should be unnecessary, will use use_utf8 attribut esetting
            #use_utf8 => 1,
        },
        sc5 => {
            url => '/main/foo_zh',
            # should be unnecessary, will use use_utf8 attribut esetting
            #use_utf8 => 1,
        },
    },
)->run;
